### ISSUE TITLE
Scores in Moodle and in report can differ

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#92] opened 2016-11-17 10:36 UTC
An example (same submission)...

```
mysql> select id,identifier,filename,reporturl,statuscode,similarityscore,attempt from mdl_plagiarism_urkund_files where id=166190\G
*************************** 1. row ***************************
             id: 166190
     identifier: 0f540a13c80a60cc5c677740681f4a6eb103ce5a
       filename: ResRep2095544m.docx
      reporturl: https://secure.urkund.com/view/23020222-964925-281286
     statuscode: Analyzed
similarityscore: 11
        attempt: 3
1 row in set (0.00 sec)
```

However, the linked report says the score is 13%. That can't be a rounding error!

![screen shot 2016-11-17 at 10 36 17](https://cloud.githubusercontent.com/assets/664139/20386040/b9f10702-acb1-11e6-98db-3261f6aabdb2.png)

**Comment by danmarsden** [comment] 2016-11-17 20:00
Probably best for you to ask Urkund directly about that one - I'd guess the first processing of the file returned an 11% similarity score via the api, but something changed and they updated the score within their system. - seems strange that it's picked up from a single source though, maybe they changed algorithms? - closing for now here but let me know if Urkund think the issue is in the plugin.

**Closed by danmarsden** 2016-11-17 20:00 UTC

**Comment by universityofglasgow** [comment] 2016-11-18 10:00
Just to confirm that Urkund have agreed that it's something at their end.
