### ISSUE TITLE
Submitting 'on behalf of' a student doesn't seem to work

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#40] opened 2015-04-01 10:47 UTC
- Log in as admin/teacher
- Pick a 'victim' student and edit their assignment. Submit a new file (on their behalf)

Urkund now behaves as though the 'submitter' (i.e. the admin/teacher) had submitted the work, not the student. No Urkund indicator appears next to the student's filename, the confirmation email is sent to the submitter and the mdl_plagiarism_urkund_files tables records the submission with the userid of the submitter not the student.

**Comment by danmarsden** [comment] 2015-04-01 21:55
Thanks Howard - I presume that's a new feature in the assignment that I haven't seen and doesn't use the "login-as" feature to submit the file?

**Comment by nomadwarmachine** [comment] 2015-04-08 10:06
Hi Dan

Yes, staff are able to edit a submission from the grading view - I've attached a couple of screen shots. I work with Howard, by the way - we're piloting Urkund for Glasgow Uni.
![assignment edit](https://cloud.githubusercontent.com/assets/11048146/7043106/014a1ac4-dddf-11e4-9451-91e8b1d8561d.png)
![assignment edit2](https://cloud.githubusercontent.com/assets/11048146/7043115/2271f5aa-dddf-11e4-82bf-386a31f0dbc6.png)

**Comment by danmarsden** [comment] 2015-04-09 00:30
Thanks - looks like this is related to the way it triggers the event in Moodle - it passes the $USER->id across as the person that triggered the event but adds an extra param "relateduserid" if the submission was for someone else:
https://github.com/moodle/moodle/blob/master/mod/assign/classes/event/assessable_submitted.php#L65

**Comment by danmarsden** [comment] 2015-04-09 01:09
....and it doesn't look like that data is passed to the legacy log eventdata :-(

I have a plan to upgrade the plugin to the new events framework but I'm hoping to get a GSOC student to do a chunk of the work first.

I've just knocked out a possible fix for this here:
https://github.com/danmarsden/moodle-plagiarism_urkund/commit/5a9bc59ab07b3f19188c5d19b703d13f51cb0425

I haven't tested that though and it will definitely need testing when groups are enabled - let me know if you get a chance to test it out and it it seems to fix it up!

thanks,

**Comment by thepurpleblob** [comment] 2015-11-27 10:39
Seems to have broken it unfortunately....

On trying to edit a student's submission...

Can not read file, either file does not exist or there are permission problems

More information about this error

Debug info: [dataroot]/filedir/b7/79/b7796a9e4ef933a86e55ed55df3aff47cb05226c
Error code: storedfilecannotread
Stack trace: 
line 187 of /lib/filestorage/stored_file.php: file_exception thrown
line 871 of /lib/filestorage/stored_file.php: call to stored_file->update()
line 424 of /lib/filelib.php: call to stored_file->set_source()
line 285 of /lib/filelib.php: call to file_prepare_draft_area()
line 163 of /mod/assign/submission/file/locallib.php: call to file_prepare_standard_filemanager()
line 248 of /mod/assign/assignmentplugin.php: call to assign_submission_file->get_form_elements()
line 6283 of /mod/assign/locallib.php: call to assign_plugin->get_form_elements_for_user()
line 6370 of /mod/assign/locallib.php: call to assign->add_plugin_submission_elements()
line 48 of /mod/assign/submission_form.php: call to assign->add_submission_form_elements()
line 191 of /lib/formslib.php: call to mod_assign_submission_form->definition()
line 3510 of /mod/assign/locallib.php: call to moodleform->moodleform()
line 532 of /mod/assign/locallib.php: call to assign->view_edit_submission_page()
line 53 of /mod/assign/view.php: call to assign->view()

**Comment by danmarsden** [comment] 2015-11-29 20:18
that error looks more like the one I would expect to see on a test system that is missing a copy of the moodledata (not related to the urkund code) but I'll take a look to see if I can reproduce it.

**Comment by thepurpleblob** [comment] 2015-11-30 09:48
Ahhh.... you could be right on the money here. I'll get it re-checked :)

**Comment by thepurpleblob** [comment] 2015-11-30 09:54
Yes - now working fine for us. Thanks :-)

**Comment by danmarsden** [comment] 2015-12-23 01:05
ah - now that we use the new Events API we should be able to access the relateduserid field - I'll try to write a patch to use this sometime soon - may not be until the new year, but I might give it a go later tonight if I can find the time.

**Closed** 2015-12-23 01:12 UTC
Labels: Bug

**Comment by danmarsden** [comment] 2015-12-23 01:13
was a pretty straight forward patch - I've just pushed an untested patch that should fix it - will unfortunately only work for "new" submissions and wont' fix up previously submitted files "on-behalf"
