### ISSUE TITLE
Warnings in my log from the Urkund plagarism plugin

### ISSUE THREAD

**Issue by johnnypraxis** [danmarsden/moodle-plagiarism_urkund#121] opened 2019-09-25 09:21 UTC
Moodle version: 3.4.3+ 
Urkund plugin version: 2018011709

Example from my log:
`PHP Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/<site-name>/moodle/plagiarism/urkund/lib.php on line 251, referer <site-name>/mod/assign/view.php?id=1013746`

`PHP Warning: simplexml_load_string(): ^ in /var/www/<site-name>/moodle/plagiarism/urkund/lib.php on line 251, referer <site-name>/mod/assign/view.php?id=1013746`

Seems like the content needs to be sanitized in some way.

**Comment by danmarsden** [comment] 2019-09-25 22:41
Hi there,

typically I'd close this without further investigation because 3.4 is no longer a supported release, and you're using a really old version of the 3.4 branch that doesn't even have the latest security patches applied.

That error suggests the response from the API call is not XML which typically means something else is also wrong - I'd need more information on how to reproduce this before investigating any further.

If you can find a way to reproduce this and provide more information about what is being returned - eg - is a server error from an internal firewall blocking the outgoing request, or is it a response from Urkund that doesn't include XML etc please provide that detail - thanks!

**Comment by lexxkoto** [comment] 2019-10-09 17:51
We're having an issue at Glasgow that is kind of related to this, but kind of isn't.

At around mid-day yesterday, the URL used by **plagiarism_urkund\task\get_scores** to get a score (as generated by **urkund_get_url()** in **plagiarism/urkund/lib.php**) stopped returning XML, and started returning JSON instead, totally breaking the Urkund plugin for us.

```
-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
[09-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): [{"Id":12345678,"ExternalId":"12345678_87654321_more_sensitive_id_data_here in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
[09-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): ^ in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
```

**Comment by urkund** [comment] 2019-10-09 19:35
> 
> 
> We're having an issue at Glasgow that is kind of related to this, but kind of isn't.
> 
> At around mid-day yesterday, the URL used by **plagiarism_urkund\task\get_scores** to get a score (as generated by **urkund_get_url()** in **plagiarism/urkund/lib.php**) stopped returning XML, and started returning JSON instead, totally breaking the Urkund plugin for us.
> 
> ```
> [09-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
> [09-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): [{"Id":12345678,"ExternalId":"12345678_87654321_more_sensitive_id_data_here in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
> [09-Oct-2019 18:22:33 Europe/London] PHP Warning:  SimpleXMLElement::__construct(): ^ in /var/www/html/moodle/plagiarism/urkund/lib.php on line 1399
> ```
> 
> Looks like Urkund are experimenting with changing their API from XML to JSON and haven't told anyone. Which isn't very nice of them.
> 
> Obviously we're taking this up with Urkund right now, but I just thought I'd let you know that they're up to something.

Hey, Simon from Urkund here.

You are correct, yesterday at around 13:00 CET we made an update to our API which unfortunately changed the default content negotiation(XML) and instead started returning JSON. This has now been remedied since the Moodle plugin here expects XML.

We can see from our logs that all post requests to the submissions resource has been accepted as normal, and next time you run cron the status of the submissions should be updated accordingly.

**Comment by danmarsden** [comment] 2019-10-09 19:58
Thanks Simon, I was just about to post asking lexxkoto to email urkund support. Might be worth looking at changing the moodle plugin code at some point to support json instead of the xml - its definitely easier to work with json!!

**Closed by danmarsden** 2019-10-09 19:58 UTC
