### ISSUE TITLE
Submitting on behalf of a student doesn't work (still/again)

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#71] opened 2016-01-07 15:47 UTC
Create a completely new Assignment, enabling Urkund but otherwise standard settings

Go to the Assignment submissions screen and pick an enrolled student. Click the edit dropdown and submit a file on their behalf.

It does not get processed by Urkund. 

Interestingly, once this has been done the student can't re-submit it either. There is no entry in the plagiarism-urkund-files table.

**Comment by danmarsden** [comment] 2016-01-08 01:49
sounds like something weird/conflicting in the events handling - I'll try to track it down and fix it in the next release.

**Comment by thepurpleblob** [comment] 2016-01-10 21:17
Just to note that (although not 100% proven) we have anecdotal evidence that this *does* work for some users, some of the time. I think there may be some subtlety in the exact settings and circumstances.

**Comment by danmarsden** [comment] 2016-01-10 21:30
cool - I can see the draft-submission setting (if enabled) interfering with this. I'm going to spend some time looking at some of this today.

**Comment by danmarsden** [comment] 2016-01-10 22:04
looks like Moodle core only triggers the assessable submitted event when draft submission is not enabled - I don't think that is correct - it means that the setting "When should the file be submitted" => "Submit the file when first uploaded" will not work.

**Comment by danmarsden** [comment] 2016-01-10 22:32
no - that's correct, it still triggers the assessable_uploaded event which is right... I can't reproduce any issues around this yet. works for me when submitting on behalf

**Comment by danmarsden** [comment] 2016-01-13 02:00
I can see a possible issue with group submissions - do the issues with submitting on-behalf happen on assignments that use group-based submissions?

**Comment by danmarsden** [comment] 2016-01-13 04:06
mentioned this in a previous commit that I was working that I thought would fix some potential issues but I had the detail wrong. (so reopening this as it was closed automatically incorrectly.)

When group submission is being used it uses the original submitter as the $userid related to the file submission - I thought about changing that to use an id from a group member but that isn't correct because when group submission is in use the file is "owned" by the original submitter (including when submitting on behalf as a teacher) - the fix was slightly different. I assume this bug I found isn't the same as the one you are having - I presume you are seeing issues with the report/score not showing to teachers/admins - but the issue I found was with the score not showing to students when team submission was enabled.

**Comment by danmarsden** [comment] 2016-01-13 04:13
I think I've reproduce this - it's slightly related to #75 - working on the best way forward now.

**Comment by thepurpleblob** [comment] 2016-01-13 06:41
These are not group submissions.

**Comment by danmarsden** [comment] 2016-01-13 06:53
thanks - I think I have the final solution... it won't fix "existing" records with a problem but I should be able to write a SQL query to find problematic records.

**Comment by danmarsden** [comment] 2016-01-13 06:54
part of the problem is that the core get_links() function called by Moodle doesn't pass the userid related to the actual submission - it passes the userid of the file "owner" which will be the admin/teacher that has uploaded the file. I looked at adding a "relateduserid" field to core but I'm going for a simpler option in the urkund code instead.

**Comment by danmarsden** [comment] 2016-01-13 06:56
-basically we use the relateduserid when creating the record in the files table so that we can get the right submission id - then we change the userid in the plagiarism table to the userid of the file owner - and allow the get_links() function to show details of files not owned by the current user - which is needed for team submissions as well. The security (can the user see the file) happens much higher in the process so we don't need to verify if the user has access to the file at this point.

**Closed** 2016-01-13 07:38 UTC

**Comment by danmarsden** [comment] 2016-01-13 07:39
This ugly looking query (that could probably be optimised a lot) should return all the files in the plagiarism_urkund_files table that have an incorrect userid set in the urkund files table.
```SQL
SELECT uf.id, uf.cm, uf.filename, uf.userid, f1.userid as userfileid FROM mdl_plagiarism_urkund_files uf
JOIN mdl_files f1 ON uf.identifier = f1.contenthash
JOIN mdl_context c1 ON c1.id = f1.contextid
AND component = 'assignsubmission_file'
AND c1.instanceid = uf.cm 
WHERE uf.id NOT IN (
SELECT p.id
FROM mdl_plagiarism_urkund_files p
JOIN mdl_files f ON p.identifier = f.contenthash
JOIN mdl_context c ON c.id = f.contextid
AND component = 'assignsubmission_file'
AND c.instanceid = p.cm 
AND p.userid = f.userid)
AND uf.statuscode <> 'pending'
```

I would not recommend a whole-sale update fixing the userid field in the urkund_files table with the userfileid value shown in that query but verifying each one and updating the userid field with the correct one shown in the userfileid but hopefully there aren't that many and you can go through each manually and verify in the interface that updating them makes the score appear correctly.

This will possibly only work in conjunction with commitid 76231db1e1e60a3a2f1e25038ea70fef4cd38b53

**Comment by danmarsden** [comment] 2016-01-13 07:42
FYI - I've also downgraded the stability of the code to "ALPHA" as this could do with some extra testing if possible. I'm working later than usual today and I want to make sure I haven't missed anything before we update the plugins db!

**Comment by danmarsden** [comment] 2016-01-13 08:06
..also might be useful to mention that the "cog" image won't show up immediately when a teacher/admin submits a file on-behalf - but it will show as soon as it has sent the file to urkund in the next cron run (scheduled to run every 5min)

**Comment by thepurpleblob** [comment] 2016-01-13 08:23
Great thanks. I'll try that query when I get into the office :)

**Comment by thepurpleblob** [comment] 2016-01-14 10:22
That took 15 minutes to run... and came up with 306 results. I'm not sure how concerned I should be. Oddly whole blocks seemed to be identical... I'll paste it all here, just to annoy Github...

9	261957	Test1.docx	3	48
1067	264139	no_extension.pdf	3	19360
1974	338369	MSc Project.docx	2055	49058
3035	380554	ECON4015_TU04GRP02.docx	9673	6867
9800	387574	The Crisis of Accountability Emerging in the Case of Stafford Hospital scandal.pdf	3432	29957
10789	390612	Philosophy 1K Essay.docx	4160	64982
10791	390612	philosophyessay.pdf	4160	42322
10794	390612	Something which is more perfect.odt	4160	62436
10795	390612	1K Essay.docx	4160	64470
10796	390612	Descartes.odt	4160	43648
10797	390612	Philosophy 1K essay.docx	4160	59333
10798	390612	Philosophy 1K Essay.docx	4160	61481
10805	391779	2M-2167755-JH.docx	4160	43427
10806	391779	content-3259-391779-4160.htm	4160	42698
10806	391779	content-3259-391779-4160.htm	4160	45774
10806	391779	content-3259-391779-4160.htm	4160	43133
10806	391779	content-3259-391779-4160.htm	4160	47637
10806	391779	content-3259-391779-4160.htm	4160	45136
10806	391779	content-3259-391779-4160.htm	4160	41533
10806	391779	content-3259-391779-4160.htm	4160	23136
10806	391779	content-3259-391779-4160.htm	4160	45966
10806	391779	content-3259-391779-4160.htm	4160	42935
10806	391779	content-3259-391779-4160.htm	4160	46523
10806	391779	content-3259-391779-4160.htm	4160	60215
10806	391779	content-3259-391779-4160.htm	4160	43052
10806	391779	content-3259-391779-4160.htm	4160	48606
10806	391779	content-3259-391779-4160.htm	4160	43183
10806	391779	content-3259-391779-4160.htm	4160	49586
10806	391779	content-3259-391779-4160.htm	4160	44450
10806	391779	content-3259-391779-4160.htm	4160	44075
10806	391779	content-3259-391779-4160.htm	4160	46477
10806	391779	content-3259-391779-4160.htm	4160	39047
10806	391779	content-3259-391779-4160.htm	4160	60448
10806	391779	content-3259-391779-4160.htm	4160	42794
10806	391779	content-3259-391779-4160.htm	4160	47528
10806	391779	content-3259-391779-4160.htm	4160	41552
10806	391779	content-3259-391779-4160.htm	4160	42415
10806	391779	content-3259-391779-4160.htm	4160	44074
10806	391779	content-3259-391779-4160.htm	4160	43132
10806	391779	content-3259-391779-4160.htm	4160	44418
10806	391779	content-3259-391779-4160.htm	4160	41151
10806	391779	content-3259-391779-4160.htm	4160	41118
10806	391779	content-3259-391779-4160.htm	4160	42695
10806	391779	content-3259-391779-4160.htm	4160	41904
10806	391779	content-3259-391779-4160.htm	4160	41518
10806	391779	content-3259-391779-4160.htm	4160	25255
10806	391779	content-3259-391779-4160.htm	4160	24694
10806	391779	content-3259-391779-4160.htm	4160	20588
10806	391779	content-3259-391779-4160.htm	4160	43296
10806	391779	content-3259-391779-4160.htm	4160	42915
10806	391779	content-3259-391779-4160.htm	4160	47674
10806	391779	content-3259-391779-4160.htm	4160	44461
10806	391779	content-3259-391779-4160.htm	4160	46106
10806	391779	content-3259-391779-4160.htm	4160	42840
10806	391779	content-3259-391779-4160.htm	4160	41426
10806	391779	content-3259-391779-4160.htm	4160	41168
10806	391779	content-3259-391779-4160.htm	4160	46469
10806	391779	content-3259-391779-4160.htm	4160	42087
10806	391779	content-3259-391779-4160.htm	4160	39153
10806	391779	content-3259-391779-4160.htm	4160	48999
10806	391779	content-3259-391779-4160.htm	4160	43125
10806	391779	content-3259-391779-4160.htm	4160	45108
10806	391779	content-3259-391779-4160.htm	4160	42163
10806	391779	content-3259-391779-4160.htm	4160	42120
10806	391779	content-3259-391779-4160.htm	4160	43375
10806	391779	content-3259-391779-4160.htm	4160	44833
10806	391779	content-3259-391779-4160.htm	4160	41886
10806	391779	content-3259-391779-4160.htm	4160	43651
10806	391779	content-3259-391779-4160.htm	4160	43210
10806	391779	content-3259-391779-4160.htm	4160	41888
10806	391779	content-3259-391779-4160.htm	4160	27420
10806	391779	content-3259-391779-4160.htm	4160	19677
10806	391779	content-3259-391779-4160.htm	4160	21232
10806	391779	content-3259-391779-4160.htm	4160	27967
10806	391779	content-3259-391779-4160.htm	4160	47524
10806	391779	content-3259-391779-4160.htm	4160	41891
10806	391779	content-3259-391779-4160.htm	4160	42167
10806	391779	content-3259-391779-4160.htm	4160	43643
10806	391779	content-3259-391779-4160.htm	4160	47778
10806	391779	content-3259-391779-4160.htm	4160	49622
10806	391779	content-3259-391779-4160.htm	4160	43283
10806	391779	content-3259-391779-4160.htm	4160	9503
10806	391779	content-3259-391779-4160.htm	4160	44309
10806	391779	content-3259-391779-4160.htm	4160	43482
10806	391779	content-3259-391779-4160.htm	4160	48230
10806	391779	content-3259-391779-4160.htm	4160	47152
10806	391779	content-3259-391779-4160.htm	4160	47527
10806	391779	content-3259-391779-4160.htm	4160	45047
10806	391779	content-3259-391779-4160.htm	4160	43266
10806	391779	content-3259-391779-4160.htm	4160	27266
10806	391779	content-3259-391779-4160.htm	4160	41122
10806	391779	content-3259-391779-4160.htm	4160	48256
10806	391779	content-3259-391779-4160.htm	4160	47671
10806	391779	content-3259-391779-4160.htm	4160	23906
10806	391779	content-3259-391779-4160.htm	4160	43211
10806	391779	content-3259-391779-4160.htm	4160	43287
10806	391779	content-3259-391779-4160.htm	4160	46667
10806	391779	content-3259-391779-4160.htm	4160	47572
10806	391779	content-3259-391779-4160.htm	4160	45772
10806	391779	content-3259-391779-4160.htm	4160	48880
10806	391779	content-3259-391779-4160.htm	4160	46013
10806	391779	content-3259-391779-4160.htm	4160	46559
10806	391779	content-3259-391779-4160.htm	4160	48066
10806	391779	content-3259-391779-4160.htm	4160	43340
10806	391779	content-3259-391779-4160.htm	4160	44568
10806	391779	content-3259-391779-4160.htm	4160	43398
10806	391779	content-3259-391779-4160.htm	4160	43872
10806	391779	content-3259-391779-4160.htm	4160	41795
10806	391779	content-3259-391779-4160.htm	4160	43374
10806	391779	content-3259-391779-4160.htm	4160	43396
10806	391779	content-3259-391779-4160.htm	4160	49000
10806	391779	content-3259-391779-4160.htm	4160	45305
10806	391779	content-3259-391779-4160.htm	4160	46651
10806	391779	content-3259-391779-4160.htm	4160	42908
10806	391779	content-3259-391779-4160.htm	4160	44377
10806	391779	content-3259-391779-4160.htm	4160	41139
10806	391779	content-3259-391779-4160.htm	4160	29927
10806	391779	content-3259-391779-4160.htm	4160	43209
10806	391779	content-3259-391779-4160.htm	4160	48489
10806	391779	content-3259-391779-4160.htm	4160	45001
10806	391779	content-3259-391779-4160.htm	4160	43126
10806	391779	content-3259-391779-4160.htm	4160	43047
10806	391779	content-3259-391779-4160.htm	4160	47783
10806	391779	content-3259-391779-4160.htm	4160	43139
10806	391779	content-3259-391779-4160.htm	4160	27988
10806	391779	content-3259-391779-4160.htm	4160	47708
10806	391779	content-3259-391779-4160.htm	4160	45307
10806	391779	content-3259-391779-4160.htm	4160	42075
10806	391779	content-3259-391779-4160.htm	4160	49001
10806	391779	content-3259-391779-4160.htm	4160	41521
10806	391779	content-3259-391779-4160.htm	4160	42146
10806	391779	content-3259-391779-4160.htm	4160	43842
10806	391779	content-3259-391779-4160.htm	4160	47784
10806	391779	content-3259-391779-4160.htm	4160	47147
10806	391779	content-3259-391779-4160.htm	4160	43581
10806	391779	content-3259-391779-4160.htm	4160	43185
10806	391779	content-3259-391779-4160.htm	4160	19550
10806	391779	content-3259-391779-4160.htm	4160	46584
10806	391779	content-3259-391779-4160.htm	4160	44205
10806	391779	content-3259-391779-4160.htm	4160	46659
10806	391779	content-3259-391779-4160.htm	4160	47291
10806	391779	content-3259-391779-4160.htm	4160	47641
10806	391779	content-3259-391779-4160.htm	4160	44820
10806	391779	content-3259-391779-4160.htm	4160	48923
10806	391779	content-3259-391779-4160.htm	4160	46474
10806	391779	content-3259-391779-4160.htm	4160	46547
10806	391779	content-3259-391779-4160.htm	4160	43665
10806	391779	content-3259-391779-4160.htm	4160	47555
10806	391779	content-3259-391779-4160.htm	4160	49674
10806	391779	content-3259-391779-4160.htm	4160	61446
10806	391779	content-3259-391779-4160.htm	4160	42841
10806	391779	content-3259-391779-4160.htm	4160	49555
10806	391779	content-3259-391779-4160.htm	4160	41588
10806	391779	content-3259-391779-4160.htm	4160	43250
10806	391779	content-3259-391779-4160.htm	4160	30900
10806	391779	content-3259-391779-4160.htm	4160	43427
10806	391779	content-3259-391779-4160.htm	4160	42164
10806	391779	content-3259-391779-4160.htm	4160	41750
10806	391779	content-3259-391779-4160.htm	4160	46961
10806	391779	content-3259-391779-4160.htm	4160	42954
10806	391779	content-3259-391779-4160.htm	4160	48555
10806	391779	content-3259-391779-4160.htm	4160	21313
10806	391779	content-3259-391779-4160.htm	4160	49304
10806	391779	content-3259-391779-4160.htm	4160	44668
10806	391779	content-3259-391779-4160.htm	4160	44078
10806	391779	content-3259-391779-4160.htm	4160	41529
10806	391779	content-3259-391779-4160.htm	4160	43663
10806	391779	content-3259-391779-4160.htm	4160	48890
10806	391779	content-3259-391779-4160.htm	4160	43054
10806	391779	content-3259-391779-4160.htm	4160	21364
10806	391779	content-3259-391779-4160.htm	4160	47091
10806	391779	content-3259-391779-4160.htm	4160	49056
10806	391779	content-3259-391779-4160.htm	4160	45309
10806	391779	content-3259-391779-4160.htm	4160	19710
10806	391779	content-3259-391779-4160.htm	4160	43766
10806	391779	content-3259-391779-4160.htm	4160	39032
10806	391779	content-3259-391779-4160.htm	4160	43107
10806	391779	content-3259-391779-4160.htm	4160	45994
10806	391779	content-3259-391779-4160.htm	4160	48318
10806	391779	content-3259-391779-4160.htm	4160	44600
10806	391779	content-3259-391779-4160.htm	4160	41987
10806	391779	content-3259-391779-4160.htm	4160	48249
10806	391779	content-3259-391779-4160.htm	4160	43684
10806	391779	content-3259-391779-4160.htm	4160	48824
10806	391779	content-3259-391779-4160.htm	4160	42416
10806	391779	content-3259-391779-4160.htm	4160	48396
10806	391779	content-3259-391779-4160.htm	4160	45061
10806	391779	content-3259-391779-4160.htm	4160	49556
10806	391779	content-3259-391779-4160.htm	4160	27429
10806	391779	content-3259-391779-4160.htm	4160	49397
10806	391779	content-3259-391779-4160.htm	4160	29959
10806	391779	content-3259-391779-4160.htm	4160	47710
10806	391779	content-3259-391779-4160.htm	4160	45403
10806	391779	content-3259-391779-4160.htm	4160	49368
10806	391779	content-3259-391779-4160.htm	4160	42414
10806	391779	content-3259-391779-4160.htm	4160	44071
10806	391779	content-3259-391779-4160.htm	4160	46615
10806	391779	content-3259-391779-4160.htm	4160	41557
10806	391779	content-3259-391779-4160.htm	4160	44031
10806	391779	content-3259-391779-4160.htm	4160	43582
10806	391779	content-3259-391779-4160.htm	4160	43106
10806	391779	content-3259-391779-4160.htm	4160	43573
10806	391779	content-3259-391779-4160.htm	4160	48562
10806	391779	content-3259-391779-4160.htm	4160	45742
10806	391779	content-3259-391779-4160.htm	4160	48825
10806	391779	content-3259-391779-4160.htm	4160	43664
10806	391779	content-3259-391779-4160.htm	4160	48965
10806	391779	content-3259-391779-4160.htm	4160	21447
10806	391779	content-3259-391779-4160.htm	4160	43272
10806	391779	content-3259-391779-4160.htm	4160	22527
10806	391779	content-3259-391779-4160.htm	4160	41553
10806	391779	content-3259-391779-4160.htm	4160	48368
10806	391779	content-3259-391779-4160.htm	4160	67590
10806	391779	content-3259-391779-4160.htm	4160	45025
10806	391779	content-3259-391779-4160.htm	4160	44314
10806	391779	content-3259-391779-4160.htm	4160	41361
10806	391779	content-3259-391779-4160.htm	4160	48398
10806	391779	content-3259-391779-4160.htm	4160	47525
10806	391779	content-3259-391779-4160.htm	4160	42277
10806	391779	content-3259-391779-4160.htm	4160	45311
10806	391779	content-3259-391779-4160.htm	4160	42148
10806	391779	content-3259-391779-4160.htm	4160	22505
10806	391779	content-3259-391779-4160.htm	4160	45492
10806	391779	content-3259-391779-4160.htm	4160	43127
10806	391779	content-3259-391779-4160.htm	4160	48397
10806	391779	content-3259-391779-4160.htm	4160	43112
10806	391779	content-3259-391779-4160.htm	4160	47074
10806	391779	content-3259-391779-4160.htm	4160	44429
10806	391779	content-3259-391779-4160.htm	4160	45177
10806	391779	content-3259-391779-4160.htm	4160	46613
10806	391779	content-3259-391779-4160.htm	4160	48600
10806	391779	content-3259-391779-4160.htm	4160	42231
10806	391779	content-3259-391779-4160.htm	4160	43782
10806	391779	content-3259-391779-4160.htm	4160	46109
10806	391779	content-3259-391779-4160.htm	4160	49705
10806	391779	content-3259-391779-4160.htm	4160	44888
10806	391779	content-3259-391779-4160.htm	4160	47076
10806	391779	content-3259-391779-4160.htm	4160	20692
10806	391779	content-3259-391779-4160.htm	4160	42178
10808	391779	2M-2136432-FP.docx	4160	46613
10809	391779	2137076 - CMR.docx	4160	45047
10810	391779	2M-2128312-JH.docx	4160	44377
13365	364845	2080662 essay.docx	67416	8591
17779	396660	plagiarism text.docx	6	49
25914	385276	2022391_econ4046_1.docx	52494	2445
29681	378438	ACCFIN5017_Group10.docx	65709	62037
30022	378438	ICM2171841 ACCFIN5017.docx	57439	56850
31711	394952	-MGT1003_Group40_1.docx	62073	43868
31874	403087	Grp 17, 18 M3 CAT task Management of tracheal collapse in dogs, info for vets.docx	24653	24588
31992	394952	MGT1003_11_1.docx	22849	60941
32103	403087	Pyothorax Pamphlet.pdf	24667	24686
32104	403087	CAT Write Up Final.docx	24667	24686
32304	394952	group 31.docx	65145	50025
32368	403087	Groups 2122 Owner leaflet.pdf	24650	24655
32632	392548	Tourism essay 2080193M.docx	30384	27815
35800	378438	ACCFIN5017_Group11.pdf	56743	53757
35802	378438	ACCFIN5017_Group 36.docx	57548	56955
35805	378438	ACCFIN5017_Group 44.pdf	65714	65973
35851	378438	ACCFIN5017-Group29.docx	56935	59496
38289	384377	ECON5002_ Group16_1and2.docx	57457	64291
38541	384377	ECON5002_Group26_1.docx	61928	65887
38693	384377	ECON5002_Group64_1.docx	55868	63511
46938	417410	2201816.pdf	61204	3281
46939	417411	2184874.doc	57459	3281
46940	417411	2203471.doc	57461	3281
46941	417412	2203471.doc	57461	3281
46942	417417	1007485.docx	9791	3281
46943	417114	2226113.docx	58190	3281
46945	417412	2173396.docx	61468	3281
46946	417412	2196457.doc	65608	3281
46947	417442	2184062.docx	57501	3281
46948	417442	2213195.doc	64653	3281
46949	417411	2029614.docx	62695	3281
46950	417411	2173396.docx	61468	3281
46951	417411	2179383.docx	60495	3281
46952	417411	2196457.docx	65608	3281
46954	417456	2184908.docx	64944	3281
46956	417020	2155785.doc	65310	3281
46957	417020	8405091.doc	29189	3281
46962	417406	2174437.docx	58414	3281
46963	417406	2220579G.docx	62275	3281
46964	417579	2178229A.docx	64940	3281
46969	417593	dummy text.docx	27	6
46969	417593	dummy text.docx	27	6
46969	417593	dummy text.docx	27	19360
46971	417602	2220579G.docx	62275	3281
46972	417593	dummy text.docx	48	6
46972	417593	dummy text.docx	48	6
46972	417593	dummy text.docx	48	19360
46974	417607	2202872.docx	63579	3281
46975	417607	2220813.docx	59644	3281
46976	417607	2227876_Draft.docx	64496	3281
46977	417607	2230564.doc	67647	3281
46980	417410	2168851.docx	58226	3281
46981	417410	2174437.docx	58414	3281
46982	417410	2190414.pdf	58018	3281
46984	417614	1007113.docx	12336	3281
46985	417614	268851.docx	58226	3281
46986	417614	2178229.docx	64940	3281
47009	417763	dummy text.docx	19360	3
47014	417769	dummy text.docx	19360	3
47044	399345	8023461P.pdf	48244	3820
48899	357309	Lynsey Burke MLM1.docx	65081	3522
48909	371138	2081432.docx	19559	27251
48909	371138	2081432.docx	19559	3191
49938	370283	CommEssay.docx	62569	3191

**Comment by danmarsden** [comment] 2016-01-14 21:26
haha - ugly looking query that doesn't even work..... :-) I'll try to write a better one!

**Comment by danmarsden** [comment] 2016-01-14 23:32
ok - take 2?

this query returns all assignment submissions that have a record in the files table matching the user in the plagiarism record (all good/correct submissions)
```SQL
SELECT uf.id
FROM mdl_plagiarism_urkund_files uf
JOIN mdl_course_modules cm on uf.cm = cm.id
JOIN mdl_modules m on m.id = cm.module
JOIN mdl_assign a ON a.id = cm.instance
JOIN mdl_assign_plugin_config ap ON ap.assignment = a.id
JOIN mdl_files f ON (f.contenthash = uf.identifier AND uf.userid = f.userid)
JOIN mdl_context c1 ON (c1.id = f.contextid AND c1.instanceid = cm.id)
WHERE m.name = 'assign' AND (ap.plugin = 'file' AND ap.subtype = 'assignsubmission' AND ap.name='enabled' and ap.value = '1')
AND f.filearea = 'submission_files'
```

And this query (hopefully) will return all assignment submission files that don't have a matching user.
```SQL
SELECT DISTINCT uf.id, uf.cm, uf.filename, uf.userid, f.userid as userfileid
FROM mdl_plagiarism_urkund_files uf
JOIN mdl_course_modules cm on uf.cm = cm.id
JOIN mdl_modules m on m.id = cm.module
JOIN mdl_assign a ON a.id = cm.instance
JOIN mdl_assign_plugin_config ap ON ap.assignment = a.id
JOIN mdl_files f ON (f.contenthash = uf.identifier)
JOIN mdl_context c1 ON (c1.id = f.contextid AND c1.instanceid = cm.id)
WHERE m.name = 'assign' AND (ap.plugin = 'file' AND ap.subtype = 'assignsubmission' AND ap.name='enabled' and ap.value = '1')
AND uf.id NOT IN(
SELECT uf.id
FROM mdl_plagiarism_urkund_files uf
JOIN mdl_course_modules cm on uf.cm = cm.id
JOIN mdl_modules m on m.id = cm.module
JOIN mdl_assign a ON a.id = cm.instance
JOIN mdl_assign_plugin_config ap ON ap.assignment = a.id
JOIN mdl_files f ON (f.contenthash = uf.identifier AND uf.userid = f.userid)
JOIN mdl_context c1 ON (c1.id = f.contextid AND c1.instanceid = cm.id)
WHERE m.name = 'assign' AND (ap.plugin = 'file' AND ap.subtype = 'assignsubmission' AND ap.name='enabled' and ap.value = '1')
AND f.filearea = 'submission_files'
)
```

If there are multiple records for the same id then there might be multiple users that have uploaded the file with the same contenthash other than the user associated with this record - hopefully it generates less records than the previous query though.

**Comment by thepurpleblob** [comment] 2016-01-15 11:15
The latter query took the same time and returned a very similar looking 311 submissions. Over 100 of them appear to be the same submission. The only thing that differs is the 'userfileid' field - not sure what when on there but it's a long-dead Assignment with submissions in groups so I'm not bothered about that. Many of the others will be old too. 

We've updated the live site to the latest master (after successful testing) so we're happy to see how we get on I think.

**Comment by danmarsden** [comment] 2016-01-17 21:10
cool - probably need to exclude "group-based" submissions from that query as well then - I'm sure I'll hear from you if you spot any other issues!

**Comment by thepurpleblob** [comment] 2016-01-18 09:57
I think we'll just see how it goes. Nothing horrible appears to have happened (yet) over the weekend and submissions seem to be going through this morning. 

I was surprised how many staff seem to have been using Assignment's "edit" feature to submit/update on behalf of students. This place can be a bit peculiar though ;-)
