### ISSUE TITLE
Assignments that have been reset no longer submit to Urkund

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#90] opened 2016-10-24 13:33 UTC
We are seeing Assignments that were used in 2015 and have now been reset (Moodle reset function) that no longer work in 2016. They have bunches of records in the urkund_files table related to students who are no longer enrolled in the course but no submissions are made for the 'new' students. 

We have been advising that a new Assignment is created but it would be better if it worked.

**Comment by danmarsden** [comment] 2016-10-25 20:19
that sounds strange.... I'd suspect the Urkund settings weren't actually enabled for those assignments - would be interesting to trace this a bit further if possible.

**Comment by thepurpleblob** [comment] 2016-10-26 10:04
There's a likely looking set of entries in the config table for this cmid. I'm pretty sure we've seen this before (but not in a terribly scientific way). Local folklore here is not to reuse assignments if they will use Urkund. I'll see if I can reliably reproduce it.

**Comment by danmarsden** [comment] 2016-10-26 20:43
it was definitely an issue you had to be aware with for the Turnitin plugins because they replicated the Course/assignment/file structure. But it "shouldn't" be a problem with Urkund as we just send the individual file and Urkund doesn't care about the course/assignment it comes from etc. Let me know if you find anything else that helps me reproduce a problem.

**Comment by danmarsden** [comment] 2016-11-17 20:01
closing here as I haven't been able to reproduce (and not enough info here to help debug further)

**Closed by danmarsden** 2016-11-17 20:01 UTC
