### ISSUE TITLE
Unable to resubmit/resend the submissions after change from disable to enable URKUND in assignment setting

### ISSUE THREAD

**Issue by sampraxis** [danmarsden/moodle-plagiarism_urkund#115] opened 2018-10-24 14:10 UTC
Scenario:

1. Create an assignment.
2. Change setting of assignment by disable URKUND (Enable URKUND: **No**)
3. Login as enrolled user.
4. Submit a file to assignment.
5. Change setting of assignment by enable URKUND (Enable URKUND: **Yes**)

Even I try to (**regenereate URKUND report**), try to run URKUND tasks and execute CRON. I still unable to get the submit file to send to URKUND or resubmit.
And I check in the database it didn't seem to create anything for that module as well.
It will be nice if it have a feature that take care of this issue.

**Comment by danmarsden** [comment] 2018-10-24 20:57
This is expected behaviour and is a duplicate of issue #100 which was closed as "won't fix" - There could be privacy related issues with this in some jurisdictions because the user is not provided with an indication that their file is being submitted to an external service for processing.

As mentioned in issue #100 feel free to contact URKUND directly about this and they may decide to fund improvements around this functionality.

**Closed by danmarsden** 2018-10-24 20:57 UTC
